import { chromium } from "playwright";
import { describe,expect,it } from "vitest";
import type { InteractionTargetIntent } from "@scry/contracts";
import { browserObservationRuntimeHealth, clickGroundedTarget, fillGroundedTarget, GroundingError, registerGroundingHistoryProvider, resolveTarget, resolveTargetLocator, verifyExpectedEffect } from "../src/grounding.js";

const intent=(concept:string,overrides:Partial<InteractionTargetIntent>={}):InteractionTargetIntent=>({concept,requiredCapabilities:["pointer_activatable"],preferredEvidence:{roles:["button"],names:[concept],labels:[],descriptions:[],placeholders:[],inputTypes:[]},scope:{kind:"page"},relations:[],prohibited:["hidden","disabled"],risk:"ordinary",confidence:{requiredFamilies:[],minimum:0.45,minimumMargin:0.05,minimumFamilyCount:2},...overrides});

describe("capability-grounded interaction",()=>{
  it("ships a self-contained browser observer runtime",()=>{const health=browserObservationRuntimeHealth();expect(health.healthy).toBe(true);expect(health.forbiddenIdentifiers).toEqual([]);});
  it("survives wrappers and rejects duplicate candidates until scoped",async()=>{const browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});try{const page=await browser.newPage();await page.setContent(`<main><div><span><button>Continue</button></span></div></main>`);expect(await(await resolveTargetLocator(page,intent("Continue"))).textContent()).toBe("Continue");await page.setContent(`<main><button>Continue</button><dialog open aria-label="Confirmation"><button>Continue</button></dialog></main>`);await expect(resolveTarget(page,intent("Continue"))).rejects.toMatchObject({code:"TARGET_AMBIGUOUS"});expect(await(await resolveTargetLocator(page,intent("Continue",{scope:{kind:"dialog",name:"Confirmation"}}))).textContent()).toBe("Continue");}finally{await browser.close();}},15_000);
  it("uses an unassociated visual label as evidence and fills the compatible input, never the label",async()=>{const browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});try{const page=await browser.newPage({viewport:{width:700,height:400}});await page.setContent(`<form><div>Password</div><div><input name="password" type="password" placeholder="Enter your password"></div></form>`);const target=intent("password_entry",{requiredCapabilities:["focusable","accepts_text","editable"],preferredEvidence:{roles:["textbox"],names:["Password"],labels:["Password"],descriptions:[],placeholders:["Enter your password"],inputTypes:["password"],visual:{sources:["geometry"],expectedText:"Password",protectedUse:false}},scope:{kind:"form"},prohibited:["hidden","disabled","readonly","display_only_text"],risk:"authentication",confidence:{requiredFamilies:[],minimumFamilyCount:3,minimumMargin:.1}});const result=await fillGroundedTarget(page,target,"protected-value");expect(result.adapter).toBe("native_fill");expect(await page.locator("input").inputValue()).toBe("protected-value");}finally{await browser.close();}},20_000);
  it("admits a canvas coordinate action only through canvas evidence and the universal gate",async()=>{const browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});try{const page=await browser.newPage();await page.setContent(`<canvas width="200" height="100" role="button" aria-label="Add"></canvas><output></output><script>document.querySelector('canvas').onclick=()=>document.querySelector('output').textContent='clicked'</script>`);const target=intent("canvas_add",{requiredCapabilities:["coordinate_action","pointer_activatable"],preferredEvidence:{roles:["button"],names:["Add"],labels:[],descriptions:[],placeholders:[],inputTypes:[],visual:{sources:["icon","canvas"],icon:"add",protectedUse:false}},confidence:{requiredFamilies:["visual"],minimum:.45,minimumMargin:0,minimumFamilyCount:2}});const result=await clickGroundedTarget(page,target);expect(result.adapter).toBe("canvas_coordinate");expect(await page.locator("output").textContent()).toBe("clicked");}finally{await browser.close();}},15_000);
  it("reports observer execution failure rather than zero candidates",async()=>{const browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});try{const page=await browser.newPage();await page.setContent(`<button>Save</button>`);await page.close();await expect(resolveTarget(page,intent("Save"))).rejects.toMatchObject({code:"OBSERVATION_FAILED",diagnostic:{observation:{status:"failed"}}});}finally{await browser.close();}},15_000);
  it("revalidates and rejects incompatible history drift",async()=>{const browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});try{const page=await browser.newPage();await page.setContent(`<button>Save</button>`);const first=await resolveTarget(page,intent("Save"));await page.setContent(`<button>Save</button>`);await expect(first.revalidate()).rejects.toMatchObject({code:"TARGET_CHANGED_BEFORE_ACTION"});registerGroundingHistoryProvider(page,async()=>({...first.diagnostic.selectedFingerprint!,digest:"f".repeat(64),capabilityDigest:"e".repeat(64)}));await expect(resolveTarget(page,intent("Save"))).rejects.toMatchObject({code:"GROUNDING_DRIFT_REQUIRES_CALIBRATION"});}finally{await browser.close();}},15_000);
  it("verifies declared effects",async()=>{const browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});try{const page=await browser.newPage();await page.setContent(`<button onclick="document.querySelector('output').textContent='Ready'">Run</button><output aria-label="Status"></output>`);await page.getByRole("button").click();const status=intent("Status",{requiredCapabilities:["readable_value"],preferredEvidence:{roles:["value"],names:["Status"],labels:[],descriptions:[],placeholders:[],inputTypes:[]},risk:"read_only",confidence:{requiredFamilies:[],minimum:.4,minimumMargin:0,minimumFamilyCount:1}});await expect(verifyExpectedEffect(page,{type:"value_change",target:status,expected:"Ready"},page.url(),500)).resolves.toBeUndefined();}finally{await browser.close();}},15_000);
});
