import { chromium, type Browser, type Page } from "playwright";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import type { InteractionTargetIntent, PraxisOperation, PraxisRequest } from "@scry/contracts";
import { checkGroundedTarget, clickGroundedTarget, fillGroundedTarget, registerGroundingHistoryProvider, resolveTarget, selectGroundedTarget, verifyExpectedEffect } from "../src/grounding.js";
import { PraxisAdapter } from "../src/praxis-adapter.js";
import { PraxisTransactionCoordinator } from "../src/praxis-transaction.js";

let browser:Browser;
beforeAll(async()=>{browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});});
afterAll(async()=>{await browser?.close();});
const identity=(name:string,role:"button"|"textbox"|"combobox"|"checkbox"|"value"="button"):InteractionTargetIntent=>({concept:name.toLowerCase().replace(/\W+/g,"_"),requiredCapabilities:role==="textbox"?["focusable","accepts_text","editable"]:role==="combobox"?["selects_option"]:role==="checkbox"?["toggleable"]:role==="value"?["readable_value"]:["pointer_activatable"],preferredEvidence:{roles:[role],names:[name],labels:[],descriptions:[],placeholders:[],inputTypes:[]},scope:{kind:"page"},relations:[],prohibited:["hidden","disabled"],risk:"ordinary",confidence:{requiredFamilies:[],minimum:.35,minimumMargin:.05,minimumFamilyCount:1}});
const request=(operation:PraxisOperation,intent:InteractionTargetIntent,expectedEffect:PraxisRequest["expectedEffect"]={type:"none"}):PraxisRequest=>({schemaVersion:1,transactionId:`tx-${operation.type}`,operationId:operation.type,intent,operation,expectedEffect,risk:intent.risk,policy:{allowedOrigins:["https://example.test"],actionTimeoutMs:1_000,totalTimeoutMs:2_000},privacy:{state:"normal",allowedChannels:["dom","accessibility"],suppressedChannels:[]},context:{pageId:"page",origin:"https://example.test",documentEpoch:0}});
async function page(html:string){const value=await browser.newPage();await value.setContent(html);return value;}
async function praxis(target:Page,input:PraxisRequest,values:Record<string,string>={}){return new PraxisTransactionCoordinator(new PraxisAdapter(target,async reference=>values[reference]??"")).execute(input,new AbortController().signal);}

describe("legacy Praxis adapter parity",()=>{
  it("matches legacy click behavior without a second dispatch",async()=>{const html=`<button onclick="out.textContent=(Number(out.textContent)||0)+1">Save</button><output id=out>0</output>`;const legacy=await page(html),wrapped=await page(html);try{await clickGroundedTarget(legacy,identity("Save"));const result=await praxis(wrapped,request({type:"activate"},identity("Save")));expect(await wrapped.locator("output").textContent()).toBe(await legacy.locator("output").textContent());expect(await wrapped.locator("output").textContent()).toBe("1");expect(result.status).toBe("succeeded");}finally{await legacy.close();await wrapped.close();}});
  it("matches fill, select, and check state",async()=>{const legacy=await page(`<input aria-label=Name><select aria-label=Country><option value=ng>Nigeria</option><option value=gh>Ghana</option></select><input type=checkbox aria-label=Agree>`),wrapped=await page(`<input aria-label=Name><select aria-label=Country><option value=ng>Nigeria</option><option value=gh>Ghana</option></select><input type=checkbox aria-label=Agree>`);try{await fillGroundedTarget(legacy,identity("Name","textbox"),"Ada");await selectGroundedTarget(legacy,identity("Country","combobox"),"gh");await checkGroundedTarget(legacy,identity("Agree","checkbox"),true);expect((await praxis(wrapped,request({type:"enter_text",input:{reference:"name",classification:"public"}},identity("Name","textbox")),{name:"Ada"})).status).toBe("succeeded");expect((await praxis(wrapped,request({type:"select_option",input:{reference:"country",classification:"public"}},identity("Country","combobox")),{country:"gh"})).status).toBe("succeeded");expect((await praxis(wrapped,request({type:"set_checked",checked:true},identity("Agree","checkbox")))).status).toBe("succeeded");expect(await wrapped.locator("input").first().inputValue()).toBe(await legacy.locator("input").first().inputValue());expect(await wrapped.locator("select").inputValue()).toBe(await legacy.locator("select").inputValue());expect(await wrapped.locator("input[type=checkbox]").isChecked()).toBe(await legacy.locator("input[type=checkbox]").isChecked());}finally{await legacy.close();await wrapped.close();}});
  it("inspects without dispatch",async()=>{const target=await page(`<output aria-label=Status>Ready</output>`);try{const result=await praxis(target,request({type:"inspect"},identity("Status","value")));expect(result).toMatchObject({status:"succeeded",mutationOutcome:"not_applied"});expect(await target.locator("output").textContent()).toBe("Ready");}finally{await target.close();}});
  it("projects legacy ambiguity and drift",async()=>{const ambiguous=await page(`<button>Save</button><button>Save</button>`);try{await expect(resolveTarget(ambiguous,identity("Save"))).rejects.toMatchObject({code:"TARGET_AMBIGUOUS"});expect(await praxis(ambiguous,request({type:"activate"},identity("Save")))).toMatchObject({status:"failed",code:"PRAXIS_TARGET_AMBIGUOUS",provenance:"intent"});}finally{await ambiguous.close();}const drift=await page(`<button>Save</button>`);try{const first=await resolveTarget(drift,identity("Save"));registerGroundingHistoryProvider(drift,async()=>({...first.diagnostic.selectedFingerprint!,digest:"f".repeat(64),capabilityDigest:"e".repeat(64)}));expect(await praxis(drift,request({type:"activate"},identity("Save")))).toMatchObject({status:"failed",code:"PRAXIS_GROUNDING_DRIFT_REQUIRES_CALIBRATION"});}finally{await drift.close();}});
  it("projects missing effects as an inconclusive mutation",async()=>{const legacy=await page(`<button>Run</button><output aria-label=Status></output>`),wrapped=await page(`<button>Run</button><output aria-label=Status></output>`);const effect={type:"value_change",target:identity("Status","value"),expected:"Ready"} as const;try{await clickGroundedTarget(legacy,identity("Run"));await expect(verifyExpectedEffect(legacy,effect,legacy.url(),120)).rejects.toMatchObject({code:"EXPECTED_EFFECT_NOT_OBSERVED"});const result=await praxis(wrapped,{...request({type:"activate"},identity("Run"),effect),policy:{allowedOrigins:["https://example.test"],actionTimeoutMs:120,totalTimeoutMs:1_000}});expect(result).toMatchObject({status:"inconclusive",code:"PRAXIS_EXPECTED_EFFECT_NOT_OBSERVED",mutationOutcome:"unknown",retry:"unsafe"});}finally{await legacy.close();await wrapped.close();}});
  it("handles protected-risk input without returning its value",async()=>{const target=await page(`<input type=password aria-label=Password>`);const intent={...identity("Password","textbox"),risk:"credential" as const,preferredEvidence:{...identity("Password","textbox").preferredEvidence,inputTypes:["password"]},confidence:{requiredFamilies:[],minimum:.35,minimumMargin:0,minimumFamilyCount:2}};try{const secret="never-serialize-this";const result=await praxis(target,request({type:"enter_text",input:{reference:"credential",classification:"known_secret"}},intent),{credential:secret});expect(result.status).toBe("succeeded");expect(await target.locator("input").inputValue()).toBe(secret);expect(JSON.stringify(result)).not.toContain(secret);}finally{await target.close();}});
});
