import { createServer, type Server } from "node:http";
import { chromium, type Browser, type BrowserContext, type Page } from "playwright";
import type { ExpectedEffect, InteractionTargetIntent, PraxisOperation, PraxisRequest, PraxisResult } from "@scry/contracts";
import { executePraxisConsumer } from "../src/praxis-consumer.js";

type Category="nested_frames"|"frame_reads"|"cross_origin"|"closed_shadow"|"popups"|"international_input"|"responsive_layout"|"contention"|"privacy"|"frame_detachment"|"delayed_frames"|"frame_navigation"|"frame_acquisition"|"frame_wait"|"cancelled_queue"|"cross_frame_ambiguity";
type InvokeOptions={effect?:ExpectedEffect;timeout?:number;signal?:AbortSignal;privacy?:PraxisRequest["privacy"]};
type Invoke=(intent:InteractionTargetIntent,operation:PraxisOperation,options?:InvokeOptions)=>Promise<PraxisResult>;
type Scenario={id:string;category:Category;path:string;run(page:Page,context:BrowserContext,invoke:Invoke):Promise<void>};
type ScenarioResult={id:string;category:Category;status:"passed"|"failed";durationMs:number;diagnostics?:unknown};
class CheckError extends Error{constructor(message:string,readonly evidence:unknown={}){super(message);this.name="CheckError";}}

const scenarios:Scenario[]=[];
const add=(category:Category,index:number,run:Scenario["run"])=>scenarios.push({id:`${category}-${index}`,category,path:`/case/${category}-${index}`,run});

for(let i=1;i<=10;i++)add("nested_frames",i,async(page,_context,invoke)=>{const result=await invoke(button(`Nested commit ${i}`),{type:"activate"},{effect:valueEffect(`nested-${i}`)});success(result);equal(await page.locator("output").textContent(),`nested-${i}`,"nested frame effect");});
for(let i=1;i<=10;i++)add("frame_reads",i,async(_page,_context,invoke)=>{const result=await invoke(read(`Frame status ${i}`),{type:"inspect"});success(result);equal(result.resolution.target.concept,`Frame status ${i}`,"frame inspection concept");});
for(let i=1;i<=10;i++)add("cross_origin",i,async(page,_context,invoke)=>{const result=await invoke(button(`Foreign commit ${i}`),{type:"activate"},{timeout:700});failure(result,"PRAXIS_NO_CAPABILITY_COMPATIBLE_CONTROL");equal(await hits(page),0,"cross-origin dispatch");});
for(let i=1;i<=10;i++)add("closed_shadow",i,async(page,_context,invoke)=>{const result=await invoke(button(`Closed action ${i}`),{type:"activate"},{timeout:700});failure(result,"PRAXIS_NO_CAPABILITY_COMPATIBLE_CONTROL");equal(await hits(page),0,"closed-shadow dispatch");});
for(let i=1;i<=10;i++)add("popups",i,async(page,context,invoke)=>{const popupReady=context.waitForEvent("page");const result=await invoke(button(`Open receipt ${i}`),{type:"activate"});success(result);const popup=await popupReady;await popup.waitForLoadState();equal(await popup.locator("h1").textContent(),`Receipt ${i}`,"popup content");equal(context.pages().length,2,"popup count");await popup.close();});
const international=["مرحبا بالعالم","こんにちは世界","नमस्ते दुनिया","שלום עולם","γειά σου κόσμε","สวัสดีชาวโลก","你好，世界","안녕하세요 세계","Привіт світе","Olá, mundo 👋🏽"];
for(let i=1;i<=10;i++)add("international_input",i,async(page,_context,invoke)=>{const value=international[i-1]!;const result=await invoke(textbox(`Localized name ${i}`),{type:"enter_text",input:{reference:`unicode-${i}`,classification:"public"}});success(result);equal(await page.locator("input").inputValue(),value,"international value");});
for(let i=1;i<=10;i++)add("responsive_layout",i,async(page,_context,invoke)=>{await page.setViewportSize({width:i%2?360:1440,height:700});const result=await invoke(button(`Responsive action ${i}`),{type:"activate"},{effect:valueEffect(`responsive-${i}`)});success(result);equal(await hits(page),1,"responsive dispatch");});
for(let i=1;i<=10;i++)add("contention",i,async(page,_context,invoke)=>{const results=await Promise.all(Array.from({length:5},(_,lane)=>invoke(button(`Lane ${i}-${lane}`,{kind:"region",name:`Region ${i}-${lane}`}),{type:"activate"})));for(const result of results)success(result);equal(await hits(page),5,"contention dispatches");});
for(let i=1;i<=10;i++)add("privacy",i,async(page,_context,invoke)=>{const result=await invoke(canvas(`Private canvas ${i}`),{type:"activate"},{privacy:{state:"normal",allowedChannels:["public_dom","accessibility"],suppressedChannels:["visual"]}});failure(result,"PRAXIS_REQUIRED_CHANNEL_FORBIDDEN");equal(await hits(page),0,"privacy dispatch");});
for(let i=1;i<=10;i++)add("frame_detachment",i,async(page,_context,invoke)=>{const result=await invoke(button(`Detach action ${i}`),{type:"activate"},{timeout:900});check(result.status!=="succeeded","detached frame succeeded",result);equal(await hits(page),0,"detached-frame application effect");if(result.code==="PRAXIS_TARGET_CHANGED_BEFORE_ACTION"){equal(result.mutationOutcome,"not_applied","pre-boundary detachment outcome");equal(result.retry,"requires_reobservation","pre-boundary detachment retry");equal(result.diagnostics.mutationBoundaryCrossed,false,"pre-boundary diagnostic");}else{equal(result.code,"PRAXIS_DISPATCH_FAILED","post-boundary detachment code");equal(result.mutationOutcome,"unknown","post-boundary detachment outcome");equal(result.retry,"unsafe","post-boundary detachment retry");equal(result.diagnostics.mutationBoundaryCrossed,true,"post-boundary diagnostic");truth(result.safeActions.includes("do_not_retry"),"post-boundary detachment retry action",result);}});
for(let i=1;i<=10;i++)add("delayed_frames",i,async(page,_context,invoke)=>{const result=await invoke(button(`Delayed frame ${i}`),{type:"activate"},{effect:valueEffect(`delayed-${i}`),timeout:1600});success(result);equal(await hits(page),1,"delayed-frame dispatch");});
for(let i=1;i<=10;i++)add("frame_navigation",i,async(page,_context,invoke)=>{await page.waitForFunction(index=>frames.length===1&&document.querySelector("iframe")?.getAttribute("data-ready")===String(index),i);const result=await invoke(button(`Navigated action ${i}`),{type:"activate"},{effect:valueEffect(`navigated-${i}`),timeout:1200});success(result);equal(await hits(page),1,"navigated-frame dispatch");});
for(let i=1;i<=10;i++)add("frame_acquisition",i,async(_page,_context,invoke)=>{const result=await invoke(read(`Acquired value ${i}`),{type:"read_value",classification:"public"});success(result);equal(result.output?.classification,"public","acquisition classification");equal(result.output?.value,`Acquired value ${i}`,"acquisition value");});
for(let i=1;i<=10;i++)add("frame_wait",i,async(_page,_context,invoke)=>{const result=await invoke({...button(`Enable action ${i}`),prohibited:["hidden"]},{type:"wait_for_state",state:"enabled"},{timeout:1200});success(result);equal(result.verification.local,"passed","frame wait verification");});
for(let i=1;i<=10;i++)add("cancelled_queue",i,async(page,_context,invoke)=>{const first=invoke(button(`Queue leader ${i}`),{type:"activate"},{effect:valueEffect(`never-${i}`),timeout:450});await page.waitForFunction(()=>window.hits===1);const controller=new AbortController();const second=invoke(button(`Queue follower ${i}`),{type:"activate"},{signal:controller.signal,timeout:700});controller.abort("certification");const follower=await second;failure(follower,"PRAXIS_CANCELLED");equal(follower.mutationOutcome,"not_started","queued cancellation mutation");const leader=await first;truth(leader.status!=="succeeded","leader unexpectedly verified",leader);equal(await hits(page),1,"queued cancellation dispatches");});
for(let i=1;i<=10;i++)add("cross_frame_ambiguity",i,async(page,_context,invoke)=>{const result=await invoke(button(`Duplicate action ${i}`),{type:"activate"},{timeout:900});failure(result,"PRAXIS_TARGET_AMBIGUOUS");equal(await hits(page),0,"ambiguous cross-frame dispatch");});

async function main(){
  check(scenarios.length===160,`expected 160 scenarios, got ${scenarios.length}`);
  const cross=await listen((request,response)=>{const url=new URL(request.url??"/","http://cross");const match=/^\/foreign\/(\d+)$/.exec(url.pathname);if(!match){response.writeHead(404).end();return;}const i=Number(match[1]);response.writeHead(200,{"content-type":"text/html"});response.end(documentPage(`<button onclick="parent.postMessage('foreign-hit','*')">Foreign commit ${i}</button>`,""));});
  const crossOrigin=origin(cross);
  const primary=await listen((request,response)=>route(request.url??"/",response,crossOrigin));
  const primaryOrigin=origin(primary);
  const browser=await chromium.launch({headless:true,channel:process.env.SCRY_BROWSER_CHANNEL??"chrome"});
  const results:ScenarioResult[]=[];let ordinal=0;
  try{
    for(const scenario of scenarios){const started=performance.now();const context=await browser.newContext();const page=await context.newPage();let last:PraxisResult|undefined;try{await page.goto(`${primaryOrigin}${scenario.path}`);const invoke:Invoke=async(intent,operation,options={})=>last=await executePraxisConsumer({page,intent,operation,expectedEffect:options.effect,signal:options.signal??new AbortController().signal,resolveInput:async reference=>international[Number(reference.split("-").pop())-1]??reference,context:{channel:"action",ordinal:++ordinal,allowedOrigins:[primaryOrigin],timeoutMs:options.timeout??1200,...(options.privacy?{privacy:options.privacy}:{})}});await scenario.run(page,context,invoke);results.push({id:scenario.id,category:scenario.category,status:"passed",durationMs:performance.now()-started});}catch(error){results.push({id:scenario.id,category:scenario.category,status:"failed",durationMs:performance.now()-started,diagnostics:{error:diagnostic(error),result:last,state:await browserState(page).catch(()=>null)}});}finally{await context.close();}}
    const endurance=await enduranceRun(browser,primaryOrigin,()=>++ordinal);
    const report={schemaVersion:1,campaign:"praxis-adversarial-certification",environment:{transport:"real_http",browser:"real_chromium",browserVersion:browser.version(),channel:process.env.SCRY_BROWSER_CHANNEL??"chrome",persistence:false,missionFlowInfrastructure:false},counts:{total:results.length,passed:results.filter(item=>item.status==="passed").length,failed:results.filter(item=>item.status==="failed").length,skipped:0},categories:Object.fromEntries([...new Set(results.map(item=>item.category))].map(category=>[category,summary(results,category)])),endurance,scenarios:results};process.stdout.write(`${JSON.stringify(report,null,2)}\n`);process.exit(report.counts.failed||!endurance.passed?1:0);
  }finally{await browser.close();await close(primary);await close(cross);}
}

async function enduranceRun(browser:Browser,baseUrl:string,next:()=>number){const context=await browser.newContext();const page=await context.newPage();await page.goto(`${baseUrl}/endurance`);const before=process.memoryUsage().rss;const durations:number[]=[];let failures=0;for(let i=0;i<1000;i++){const started=performance.now();const result=await executePraxisConsumer({page,intent:button("Endurance commit"),operation:{type:"activate"},signal:new AbortController().signal,context:{channel:"action",ordinal:next(),allowedOrigins:[baseUrl],timeoutMs:800}});durations.push(performance.now()-started);if(result.status!=="succeeded")failures++;}const dispatchCount=await hits(page);const after=process.memoryUsage().rss;await context.close();const memoryGrowthRatio=(after-before)/Math.max(before,1);return{iterations:1000,failures,dispatchCount,memoryGrowthRatio,p50:percentile(durations,.5),p95:percentile(durations,.95),passed:failures===0&&dispatchCount===1000&&memoryGrowthRatio<=.30};}

function route(rawUrl:string,response:import("node:http").ServerResponse,crossOrigin:string){const url=new URL(rawUrl,"http://primary");if(url.pathname==="/endurance"){respond(response,documentPage(`<button onclick="window.hits++">Endurance commit</button>`,`window.hits=0`));return;}const match=/^\/case\/([a-z_]+)-(\d+)$/.exec(url.pathname);if(match){const category=match[1] as Category,index=Number(match[2]);respond(response,scenarioPage(category,index,crossOrigin));return;}const child=/^\/frame\/([a-z_]+)\/(\d+)(?:\/(\d+))?$/.exec(url.pathname);if(child){respond(response,framePage(child[1] as Category,Number(child[2]),Number(child[3]??1)));return;}const popup=/^\/popup\/(\d+)$/.exec(url.pathname);if(popup){respond(response,documentPage(`<h1>Receipt ${popup[1]}</h1>`,""));return;}response.writeHead(404).end();}
function scenarioPage(category:Category,i:number,crossOrigin:string){switch(category){
  case"nested_frames":return parent(`<iframe src="/frame/nested_frames/${i}/1"></iframe><output data-scry-readable>idle</output>`,`addEventListener('message',e=>{if(e.data==='nested-${i}'){hits++;document.querySelector('output').textContent=e.data}})`);
  case"frame_reads":return parent(`<iframe src="/frame/frame_reads/${i}"></iframe>`,"");
  case"cross_origin":return parent(`<iframe src="${crossOrigin}/foreign/${i}"></iframe><output>idle</output>`,`addEventListener('message',()=>hits++)`);
  case"closed_shadow":return parent(`<div id="host"></div>`,`const root=document.querySelector('#host').attachShadow({mode:'closed'});const b=document.createElement('button');b.textContent='Closed action ${i}';b.onclick=()=>hits++;root.append(b)`);
  case"popups":return parent(`<button>Open receipt ${i}</button>`,`document.querySelector('button').onclick=()=>{hits++;open('/popup/${i}','_blank')}`);
  case"international_input":return parent(`<label>Localized name ${i}<input aria-label="Localized name ${i}"></label>`,"");
  case"responsive_layout":return parent(`<button>Responsive action ${i}</button><output data-scry-readable>idle</output>`,`document.querySelector('button').onclick=()=>{hits++;document.querySelector('output').textContent='responsive-${i}'}`);
  case"contention":return parent(`${Array.from({length:5},(_,lane)=>`<section aria-label="Region ${i}-${lane}"><button>Lane ${i}-${lane}</button></section>`).join("")}<output>0</output>`,`document.querySelectorAll('button').forEach(b=>b.onclick=()=>{hits++;document.querySelector('output').textContent=String(hits)})`);
  case"privacy":return parent(`<canvas width="300" height="80"></canvas>`,`const c=document.querySelector('canvas'),x=c.getContext('2d');x.font='20px sans-serif';x.fillText('Private canvas ${i}',20,45);c.onclick=()=>hits++`);
  case"frame_detachment":return parent(`<iframe id="target" src="/frame/frame_detachment/${i}"></iframe>`,`addEventListener('message',e=>{if(e.data==='detach')document.querySelector('#target').remove();if(e.data==='hit')hits++})`);
  case"delayed_frames":return parent(`<main id="mount"><output data-scry-readable>idle</output></main>`,`setTimeout(()=>{const f=document.createElement('iframe');f.src='/frame/delayed_frames/${i}';document.querySelector('#mount').prepend(f)},${80+i*5});addEventListener('message',e=>{if(e.data==='delayed-${i}'){hits++;document.querySelector('output').textContent=e.data}})`);
  case"frame_navigation":return parent(`<iframe id="target" src="/frame/frame_navigation/${i}/1"></iframe><output data-scry-readable>idle</output>`,`addEventListener('message',e=>{if(e.data==='ready-${i}'){document.querySelector('#target').dataset.ready='${i}'}if(e.data==='navigated-${i}'){hits++;document.querySelector('output').textContent=e.data}})`);
  case"frame_acquisition":return parent(`<iframe src="/frame/frame_acquisition/${i}"></iframe>`,"");
  case"frame_wait":return parent(`<iframe src="/frame/frame_wait/${i}"></iframe>`,"");
  case"cancelled_queue":return parent(`<button>Queue leader ${i}</button><button>Queue follower ${i}</button>`,`document.querySelectorAll('button').forEach(b=>b.onclick=()=>hits++)`);
  case"cross_frame_ambiguity":return parent(`<iframe src="/frame/cross_frame_ambiguity/${i}/1"></iframe><iframe src="/frame/cross_frame_ambiguity/${i}/2"></iframe>`,`addEventListener('message',()=>hits++)`);
}}
function framePage(category:Category,i:number,level:number){switch(category){case"nested_frames":return level===1?documentPage(`<iframe src="/frame/nested_frames/${i}/2"></iframe>`,""):documentPage(`<button>Nested commit ${i}</button>`,`document.querySelector('button').onclick=()=>top.postMessage('nested-${i}','*')`);case"frame_reads":return documentPage(`<output aria-label="Frame status ${i}">Frame status ${i}</output>`,"");case"frame_detachment":return documentPage(`<button>Detach action ${i}</button>`,`document.querySelector('button').onpointerover=()=>parent.document.querySelector('#target').remove();document.querySelector('button').onclick=()=>parent.postMessage('hit','*')`);case"delayed_frames":return documentPage(`<button>Delayed frame ${i}</button>`,`document.querySelector('button').onclick=()=>top.postMessage('delayed-${i}','*')`);case"frame_navigation":return documentPage(`<button>Navigated action ${i}</button>`,`parent.postMessage('ready-${i}','*');document.querySelector('button').onclick=()=>parent.postMessage('navigated-${i}','*')`);case"frame_acquisition":return documentPage(`<output aria-label="Acquired value ${i}">Acquired value ${i}</output>`,"");case"frame_wait":return documentPage(`<button disabled>Enable action ${i}</button>`,`setTimeout(()=>document.querySelector('button').disabled=false,${80+i*4})`);case"cross_frame_ambiguity":return documentPage(`<button>Duplicate action ${i}</button>`,`document.querySelector('button').onclick=()=>parent.postMessage('duplicate','*')`);default:return documentPage("","");}}

function parent(body:string,script:string){return documentPage(body,`window.hits=0;${script}`);}function documentPage(body:string,script:string){return`<!doctype html><html><head><meta charset="utf-8"><style>body{font:16px system-ui;margin:20px}button,input,canvas{font:inherit;padding:10px;margin:8px}iframe{width:520px;height:180px;border:1px solid #888}</style></head><body>${body}<script>${script}</script></body></html>`;}function respond(response:import("node:http").ServerResponse,body:string){response.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});response.end(body);}async function listen(handler:Parameters<typeof createServer>[0]){const server=createServer(handler);await new Promise<void>((resolve,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",resolve)});return server;}function origin(server:Server){const address=server.address();if(!address||typeof address==="string")throw new Error("server address unavailable");return`http://127.0.0.1:${address.port}`;}async function close(server:Server){await new Promise<void>(resolve=>server.close(()=>resolve()));}
function base(concept:string,capabilities:InteractionTargetIntent["requiredCapabilities"],scope:InteractionTargetIntent["scope"]={kind:"page"}):InteractionTargetIntent{return{concept,requiredCapabilities:capabilities,preferredEvidence:{roles:[],names:[concept],labels:[concept],descriptions:[],placeholders:[],inputTypes:[]},scope,relations:[],prohibited:["hidden","disabled"],risk:"ordinary",confidence:{requiredFamilies:[]}};}function button(name:string,scope?:InteractionTargetIntent["scope"]):InteractionTargetIntent{return{...base(name,["pointer_activatable"],scope),preferredEvidence:{roles:["button"],names:[name],labels:[],descriptions:[],placeholders:[],inputTypes:[]}};}function textbox(name:string):InteractionTargetIntent{return{...base(name,["focusable","accepts_text","editable"]),preferredEvidence:{roles:["textbox"],names:[name],labels:[name],descriptions:[],placeholders:[],inputTypes:[]}};}function read(value:string):InteractionTargetIntent{return{...base(value,["readable_value"]),risk:"read_only",preferredEvidence:{roles:["value"],names:[value],labels:[],descriptions:[],placeholders:[],inputTypes:[],expectedText:value}};}function canvas(name:string):InteractionTargetIntent{return{...base(name,["coordinate_action"]),preferredEvidence:{roles:[],names:[],labels:[],descriptions:[],placeholders:[],inputTypes:[],visual:{sources:["canvas"],expectedText:name,protectedUse:false}},confidence:{requiredFamilies:["visual"],minimumFamilyCount:1}};}function valueEffect(value:string):ExpectedEffect{return{type:"value_change",target:read(value),expected:value};}
function success(result:PraxisResult):asserts result is Extract<PraxisResult,{status:"succeeded"}>{check(result.status==="succeeded","expected success",result);}function failure(result:PraxisResult,code:string):asserts result is Exclude<PraxisResult,{status:"succeeded"}>{check(result.status!=="succeeded",`expected failure ${code}`,result);equal(result.code,code,"failure code");}function check(value:unknown,message:string,evidence:unknown={}){if(!value)throw new CheckError(message,evidence);}function truth(value:unknown,message:string,evidence:unknown={}){check(value,message,evidence);}function equal(actual:unknown,expected:unknown,message:string){if(!Object.is(actual,expected))throw new CheckError(`${message}: expected ${String(expected)}, got ${String(actual)}`);}async function hits(page:Page){return page.evaluate(()=>Number((window as unknown as{hits?:number}).hits??0));}async function browserState(page:Page){return page.evaluate(()=>({url:location.href,text:document.body.innerText,hits:Number((window as unknown as{hits?:number}).hits??0),frames:document.querySelectorAll("iframe").length}));}function diagnostic(error:unknown){return error instanceof CheckError?{name:error.name,message:error.message,evidence:error.evidence}:error instanceof Error?{name:error.name,message:error.message}:String(error);}function summary(results:ScenarioResult[],category:Category){const selected=results.filter(item=>item.category===category);return{total:selected.length,passed:selected.filter(item=>item.status==="passed").length,failed:selected.filter(item=>item.status==="failed").length};}function percentile(values:number[],quantile:number){const sorted=[...values].sort((a,b)=>a-b);return sorted[Math.min(sorted.length-1,Math.floor(sorted.length*quantile))]??0;}

(process.stdout as typeof process.stdout&{_handle?:{setBlocking?(value:boolean):void}})._handle?.setBlocking?.(true);
await main();
