import { createHash } from "node:crypto";
import type { CandidateEvidence, ControlCapabilities, DriftClassification, EvidenceFamily, ExpectedEffect, InteractionAdapter, InteractionTargetIntent, SemanticFingerprint, SemanticRelation } from "@scry/contracts";
import { chromium, type Locator, type Page } from "playwright";
import { resolveVisualAnchors } from "./visual-grounding.js";
import { inspectBrowserRuntimeArtifacts, playwrightBrowserChannel, visualRedactionInitScript } from "./browser-runtime-artifacts.js";
import { PraxisGroundingPolicyV1 } from "./praxis-observation.js";
import { collectPraxisEvidence } from "./praxis-evidence.js";

type SafeAction="narrow_scope"|"revise_intent"|"retry_after_render"|"request_calibration"|"check_executor_health"|"use_supported_capability";
export type GroundingScore={families:Partial<Record<EvidenceFamily,number>>;familyCount:number;total:number};
export type GroundingDiagnostic={candidateCount:number;eligibleCount:number;confidence:number;confidenceMargin:number;scope:InteractionTargetIntent["scope"];selectedFingerprint?:SemanticFingerprint;score?:GroundingScore;rejectedConstraints:string[];drift:DriftClassification;safeActions:SafeAction[];resolutionSource:"unified";visualCandidateCount:number;observation:{status:"succeeded"|"failed";phase?:string;reasonCode?:string};evidenceFamilies?:EvidenceFamily[];correlationGroups?:string[];degradedPolicy?:string;selectedAdapter?:InteractionAdapter};
export type GroundingResult={locator:Locator;diagnostic:GroundingDiagnostic;adapter:InteractionAdapter;actionPoint?:{x:number;y:number};revalidate():Promise<void>};

export type ObservedControl={runtimeId:string;tag:string;role:string;name:string;accessibilityRole:string;accessibilityName:string;labels:string[];description:string;text:string;placeholder:string;inputType:string;context:string;path:string[];bounds:{x:number;y:number;width:number;height:number};capabilities:ControlCapabilities;relationMatches:boolean[]};
type Candidate={locator:Locator;meta:ObservedControl;evidence:CandidateEvidence[];score:GroundingScore;fingerprint:SemanticFingerprint;adapter:InteractionAdapter;actionPoint?:{x:number;y:number}};
const observers=new WeakMap<Page,(diagnostic:GroundingDiagnostic&{intentDigest:string;outcome:"resolved"|"rejected";code?:string})=>void|Promise<void>>();
const historyProviders=new WeakMap<Page,(intentDigest:string)=>Promise<SemanticFingerprint|undefined>>();
export function registerGroundingObserver(page:Page,observer:(diagnostic:GroundingDiagnostic&{intentDigest:string;outcome:"resolved"|"rejected";code?:string})=>void|Promise<void>){observers.set(page,observer);}
export function registerGroundingHistoryProvider(page:Page,provider:(intentDigest:string)=>Promise<SemanticFingerprint|undefined>){historyProviders.set(page,provider);}

export async function resolveTarget(page:Page,intent:InteractionTargetIntent):Promise<GroundingResult>{
  const intentDigest=createHash("sha256").update(stableJson(intent)).digest("hex");
  const history=await historyProviders.get(page)?.(intentDigest);
  let scope:Locator;let controls:Locator;let count=0;
  try{scope=await resolveScope(page,intent.scope);controls=scope.locator("input, textarea, select, button, a[href], canvas, [role], [contenteditable='true'], [tabindex]:not([tabindex='-1']), output, code, pre, dd, dt, main, section, p, span, div, h1, h2, h3, h4, h5, h6, [data-scry-readable]");count=Math.min(await controls.count(),PraxisGroundingPolicyV1.candidateLimit);}catch(error){if(error instanceof GroundingError)throw error;return throwObservation(page,intentDigest,intent,count,"execution",error);}
  const candidates:Candidate[]=[];const rejected=new Set<string>();let visualDegraded=false;
  let anchors:Awaited<ReturnType<typeof resolveVisualAnchors>>=[];
  try{anchors=await resolveVisualAnchors(page,scope,intent);}catch(error){if(!degradedPermitted(intent,"visual"))return throwObservation(page,intentDigest,intent,count,"mapping",error);visualDegraded=true;}
  for(let index=0;index<count;index+=1){
    const locator=controls.nth(index);let meta:ObservedControl;
    try{meta=await locator.evaluate(observeControlInPage,intent.relations);if(meta.capabilities.canFocus||meta.role||meta.name){const snapshot=await locator.ariaSnapshot({timeout:1_000}).catch(()=>"");const parsed=parseAriaSnapshot(snapshot);meta.accessibilityRole=parsed.role;meta.accessibilityName=parsed.name;}}catch(error){return throwObservation(page,intentDigest,intent,count,"execution",error);}
    const violations=capabilityViolations(intent,meta);
    if(violations.length){violations.forEach((item)=>rejected.add(item));continue;}
    const evidence=collectPraxisEvidence(intent,meta,anchors);
    const score=scoreEvidence(intent,evidence);
    const candidateFingerprint=fingerprint(intent,meta);
    const canvasAnchor=meta.tag==="canvas"?anchors.find((anchor)=>anchor.bounds.x>=meta.bounds.x&&anchor.bounds.y>=meta.bounds.y&&anchor.bounds.x+anchor.bounds.width<=meta.bounds.x+meta.bounds.width&&anchor.bounds.y+anchor.bounds.height<=meta.bounds.y+meta.bounds.height):undefined;
    const actionPoint=canvasAnchor?{x:canvasAnchor.bounds.x+canvasAnchor.bounds.width/2-meta.bounds.x,y:canvasAnchor.bounds.y+canvasAnchor.bounds.height/2-meta.bounds.y}:undefined;
    candidates.push({locator,meta,evidence,score,fingerprint:candidateFingerprint,adapter:selectAdapter(intent,meta),...(actionPoint?{actionPoint}:{})});
  }
  candidates.sort((a,b)=>b.score.total-a.score.total||a.fingerprint.digest.localeCompare(b.fingerprint.digest));
  const policy=riskPolicy(intent);const best=candidates[0];const confidence=best?.score.total??0;const margin=best?confidence-(candidates[1]?.score.total??0):0;
  const drift:DriftClassification=!history||history.digest===best?.fingerprint.digest?"unchanged":best&&best.score.total>=policy.minimum+.1&&history.capabilityDigest===best.fingerprint.capabilityDigest?"compatible":best&&best.score.total>=policy.minimum?"suspicious":"incompatible";
  const base:GroundingDiagnostic={candidateCount:count,eligibleCount:candidates.length,confidence,confidenceMargin:margin,scope:intent.scope,rejectedConstraints:[...rejected],drift,safeActions:[],resolutionSource:"unified",visualCandidateCount:anchors.length,observation:{status:"succeeded"},...(visualDegraded?{degradedPolicy:"visual_unavailable_remaining_channels_authoritative"}:{}),...(best?{score:best.score,evidenceFamilies:Object.keys(best.score.families)as EvidenceFamily[],correlationGroups:[...new Set(best.evidence.map((item)=>item.correlationGroup))],selectedAdapter:best.adapter}:{})};
  if(count===0)throw await reject(page,intentDigest,"CONTROL_INVENTORY_EMPTY",{...base,safeActions:["revise_intent","retry_after_render"]});
  if(!best)throw await reject(page,intentDigest,"NO_CAPABILITY_COMPATIBLE_CONTROL",{...base,safeActions:["revise_intent","narrow_scope"]});
  const hasIdentityEvidence=Boolean(best.score.families.accessibility||best.score.families.textual||best.score.families.visual||best.score.families.historical||best.score.families.runtime||(intent.relations.length>0&&best.meta.relationMatches.every(Boolean)));
  const missingFamilies=intent.confidence.requiredFamilies.filter((family)=>!best.score.families[family]||best.score.families[family]!<.55);
  if(!hasIdentityEvidence||confidence<policy.minimum||best.score.familyCount<policy.familyCount||missingFamilies.length)throw await reject(page,intentDigest,"INSUFFICIENT_EVIDENCE",{...base,rejectedConstraints:[...base.rejectedConstraints,...(!hasIdentityEvidence?["identity_evidence"]:[]),...missingFamilies.map((family)=>`evidence_family:${family}`)],selectedFingerprint:best.fingerprint,safeActions:["narrow_scope","request_calibration"]});
  if(candidates.length>1&&(margin<=0||margin<policy.margin))throw await reject(page,intentDigest,"TARGET_AMBIGUOUS",{...base,selectedFingerprint:best.fingerprint,safeActions:["narrow_scope","request_calibration"]});
  if(drift==="suspicious"||drift==="incompatible")throw await reject(page,intentDigest,"GROUNDING_DRIFT_REQUIRES_CALIBRATION",{...base,selectedFingerprint:best.fingerprint,safeActions:["request_calibration","revise_intent"]});
  const diagnostic={...base,selectedFingerprint:best.fingerprint,safeActions:[]};
  await observers.get(page)?.({...diagnostic,intentDigest,outcome:"resolved"});
  return{locator:best.locator,adapter:best.adapter,diagnostic,...(best.actionPoint?{actionPoint:best.actionPoint}:{}),async revalidate(){
    let current:ObservedControl;try{current=await best.locator.evaluate(observeControlInPage,intent.relations);}catch{throw new GroundingError("TARGET_CHANGED_BEFORE_ACTION",{...diagnostic,safeActions:["retry_after_render","request_calibration"]});}
    if(current.runtimeId!==best.meta.runtimeId||capabilityViolations(intent,current).length||fingerprint(intent,current).digest!==best.fingerprint.digest)throw new GroundingError("TARGET_CHANGED_BEFORE_ACTION",{...diagnostic,safeActions:["retry_after_render","request_calibration"]});
  }};
}

export async function resolveTargetLocator(page:Page,intent:InteractionTargetIntent){const result=await resolveTarget(page,intent);await result.revalidate();return result.locator;}
export async function clickGroundedTarget(page:Page,intent:InteractionTargetIntent,options:{timeout?:number}={}){const result=await resolveTarget(page,intent);await result.revalidate();try{await result.locator.click(result.adapter==="canvas_coordinate"&&result.actionPoint?{...options,position:result.actionPoint}:options);}catch{throw new GroundingError("INTERACTION_DISPATCH_FAILED",result.diagnostic);}return result;}
export async function fillGroundedTarget(page:Page,intent:InteractionTargetIntent,value:string,options:{timeout?:number}={}){const result=await resolveTarget(page,intent);await result.revalidate();try{if(result.adapter==="native_fill")await result.locator.fill(value,options);else{await result.locator.focus(options);if(result.adapter==="content_editable")await result.locator.press(process.platform==="darwin"?"Meta+A":"Control+A",options);await page.keyboard.insertText(value);}}catch{throw new GroundingError("INTERACTION_DISPATCH_FAILED",result.diagnostic);}const confirmed=await result.locator.evaluate((element)=>{const item=element as HTMLInputElement;return"value"in item?item.value.length>0:(element.textContent??"").length>0;}).catch(()=>false);if(!confirmed)throw new GroundingError("LOCAL_STATE_NOT_OBSERVED",result.diagnostic);return result;}
export async function selectGroundedTarget(page:Page,intent:InteractionTargetIntent,value:string,options:{timeout?:number}={}){const result=await resolveTarget(page,intent);await result.revalidate();try{await result.locator.selectOption(value,options);}catch{throw new GroundingError("INTERACTION_DISPATCH_FAILED",result.diagnostic);}if(await result.locator.inputValue()!==value)throw new GroundingError("LOCAL_STATE_NOT_OBSERVED",result.diagnostic);return result;}
export async function checkGroundedTarget(page:Page,intent:InteractionTargetIntent,checked:boolean,options:{timeout?:number}={}){const result=await resolveTarget(page,intent);await result.revalidate();try{await result.locator.setChecked(checked,options);}catch{throw new GroundingError("INTERACTION_DISPATCH_FAILED",result.diagnostic);}if(await result.locator.isChecked()!==checked)throw new GroundingError("LOCAL_STATE_NOT_OBSERVED",result.diagnostic);return result;}
export function armExpectedEffect(page:Page,effect:ExpectedEffect,timeoutMs=10_000):Promise<void>|undefined{if(effect.type!=="network_outcome")return;return page.waitForResponse((response)=>{const request=response.request();return response.url().includes(effect.urlPattern)&&(!effect.method||request.method().toLowerCase()===effect.method.toLowerCase())&&response.status()>=effect.statusMin&&response.status()<=effect.statusMax;},{timeout:timeoutMs}).then(()=>undefined);}
export async function verifyExpectedEffect(page:Page,effect:ExpectedEffect,beforeUrl:string,timeoutMs=10_000,armed?:Promise<void>){
  if(effect.type==="none")return;if(effect.type==="network_outcome"){try{await(armed??Promise.reject());return;}catch{throw new ExpectedEffectError("EXPECTED_EFFECT_NOT_OBSERVED");}}
  const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){try{
    if(effect.type==="navigation"){const current=page.url();if(!effect.url&&current!==beforeUrl)return;if(effect.url){const expected=new URL(effect.url,beforeUrl);const actual=new URL(current);if(effect.match==="exact"&&actual.href===expected.href||effect.match==="path"&&actual.pathname+actual.search===expected.pathname+expected.search||effect.match==="contains"&&actual.href.includes(effect.url))return;}}
    if(effect.type==="visibility_change"&&await(await resolveTargetLocator(page,effect.target)).isVisible()===effect.visible)return;
    if(effect.type==="value_change"){const target=await resolveTargetLocator(page,effect.target);const value=await target.inputValue().catch(()=>target.textContent().then((v)=>v??""));if(effect.expected===undefined?value.length>0:value===effect.expected)return;}
    if(effect.type==="state_change"){const target=await resolveTargetLocator(page,effect.target);if((effect.checked===undefined||await target.isChecked()===effect.checked)&&(effect.enabled===undefined||await target.isEnabled()===effect.enabled))return;}
    if(effect.type==="new_region"&&await(await resolveTargetLocator(page,effect.target)).isVisible())return;
  }catch{}await page.waitForTimeout(100);}throw new ExpectedEffectError("EXPECTED_EFFECT_NOT_OBSERVED");
}

export function browserObservationRuntimeHealth(){const source=observeControlInPage.toString();const inspected=inspectBrowserRuntimeArtifacts({observer:source,privacyInjection:visualRedactionInitScript});return{...inspected,forbiddenIdentifiers:["__name"].filter((item)=>source.includes(item)||visualRedactionInitScript.includes(item)),health:{observer:inspected.healthy?"healthy":"failed",accessibilityMapper:inspected.healthy?"healthy":"failed",geometryResolver:"healthy",ocr:"healthy",privacyInjection:inspected.healthy?"healthy":"failed"}as const};}

export async function verifyBrowserObservationRuntime(browserChannel?:string){
  const staticHealth=browserObservationRuntimeHealth();
  if(!staticHealth.healthy)return staticHealth;
  const diagnostics=[...staticHealth.diagnostics];let browser;
  try{
    const launchChannel=playwrightBrowserChannel(browserChannel);browser=await chromium.launch({headless:true,...(launchChannel?{channel:launchChannel}:{})});
    const context=await browser.newContext();await context.addInitScript({content:visualRedactionInitScript});
    const page=await context.newPage();const pageErrors:string[]=[];page.on("pageerror",error=>pageErrors.push(error.message));
    await page.goto('data:text/html,<label for="runtime-check">Runtime check</label><input id="runtime-check" placeholder="Runtime check">');
    const observed=await page.locator("#runtime-check").evaluate(observeControlInPage,[]);
    if(!observed.capabilities.canAcceptText||!observed.capabilities.editable)diagnostics.push({code:"BROWSER_RUNTIME_SCHEMA_INVALID",subsystem:"observer",message:"Observer health fixture did not report required text-entry capabilities."});
    if(!await page.locator("#scry-visual-redaction-style").count())diagnostics.push({code:"BROWSER_RUNTIME_INJECTION_FAILED",subsystem:"privacyInjection",message:"Privacy initialization artifact was not installed."});
    for(const message of pageErrors)diagnostics.push({code:"BROWSER_RUNTIME_PAGE_ERROR",subsystem:"observer",message:/__name/.test(message)?"Transpiler helper escaped into the browser runtime.":"Browser runtime health fixture emitted a page error."});
    await context.close();
  }catch(error){const unavailable=error instanceof Error&&error.message.includes("Executable doesn't exist");diagnostics.push({code:unavailable?"BROWSER_EXECUTABLE_UNAVAILABLE":"BROWSER_RUNTIME_EXECUTION_FAILED",subsystem:"observer",message:unavailable?"The configured browser executable is unavailable.":"The production browser could not execute the observation artifact."});}
  finally{await browser?.close().catch(()=>undefined);}
  const healthy=diagnostics.length===0;
  return{...staticHealth,healthy,diagnostics,health:{...staticHealth.health,observer:healthy?"healthy" as const:"failed" as const,accessibilityMapper:healthy?"healthy" as const:"failed" as const,privacyInjection:healthy?"healthy" as const:"failed" as const}};
}

async function resolveScope(page:Page,scope:InteractionTargetIntent["scope"]):Promise<Locator>{
  const parent=scope.within?await resolveScope(page,scope.within):page.locator("body");if(scope.kind==="page")return parent;
  const selector:{[key:string]:string}={dialog:"dialog,[role=dialog]",form:"form,[role=form]",field_group:"fieldset,[role=group],div",table:"table,[role=table]",row:"tr,[role=row]",region:"section,main,aside,[role=region]",recently_changed:"[data-scry-recently-changed]"};
  const options=parent.locator(selector[scope.kind]??"*");if(!scope.name){if(await options.count()===1)return options;throw new GroundingError("TARGET_SCOPE_INVALID",emptyDiagnostic(scope,await options.count()));}
  const matches:number[]=[];for(let index=0,count=Math.min(await options.count(),500);index<count;index+=1){const candidate=options.nth(index);const identity=await candidate.evaluate((element)=>`${element.getAttribute("aria-label")??""} ${element.getAttribute("title")??""} ${element.textContent??""}`.replace(/\s+/g," ").trim()).catch(()=>"");if(normalize(identity).includes(normalize(scope.name)))matches.push(index);}if(matches.length===1)return options.nth(matches[0]!);throw new GroundingError("TARGET_SCOPE_INVALID",emptyDiagnostic(scope,matches.length));
}

/** This function is serialized into the page. It must remain self-contained and free of local named helpers. */
function observeControlInPage(element:Element,relations:SemanticRelation[]):ObservedControl{
  const state=globalThis as typeof globalThis&{__scryGroundingIds?:WeakMap<Element,string>;__scryGroundingSequence?:number};state.__scryGroundingIds??=new WeakMap();state.__scryGroundingSequence??=0;let runtimeId=state.__scryGroundingIds.get(element);if(!runtimeId){state.__scryGroundingSequence+=1;runtimeId=`control-${state.__scryGroundingSequence}`;state.__scryGroundingIds.set(element,runtimeId);}
  const html=element as HTMLElement;const input=element as HTMLInputElement;const tag=element.tagName.toLowerCase();const attrRole=(element.getAttribute("role")??"").trim();let role=attrRole;if(!role){if(tag==="button")role="button";else if(tag==="a")role="link";else if(tag==="select")role="combobox";else if(tag==="textarea"||tag==="input")role=input.type==="checkbox"?"checkbox":input.type==="radio"?"radio":"textbox";}
  const labels:string[]=[];if("labels"in input&&input.labels)for(const label of Array.from(input.labels))labels.push((label.textContent??"").replace(/\s+/g," ").trim().slice(0,500));const labelledBy=(element.getAttribute("aria-labelledby")??"").split(/\s+/);for(const id of labelledBy){const item=element.ownerDocument.getElementById(id);if(item)labels.push((item.textContent??"").replace(/\s+/g," ").trim().slice(0,500));}
  const placeholder=(element.getAttribute("placeholder")??"").trim();const name=(element.getAttribute("aria-label")??labels[0]??element.getAttribute("title")??placeholder??"").trim();const style=getComputedStyle(html);const rect=html.getBoundingClientRect();const visible=style.visibility!=="hidden"&&style.display!=="none"&&rect.width>0&&rect.height>0;const disabled="disabled"in input&&Boolean(input.disabled);const readonly="readOnly"in input&&Boolean(input.readOnly);const contentEditable=html.isContentEditable;const nativeText=tag==="textarea"||tag==="input"&&!['button','submit','reset','checkbox','radio','file','range','color','hidden'].includes(input.type);const interactiveRole=["button","link","checkbox","radio","switch","combobox","listbox","option","menuitem","tab"].includes(role);const pointerInteractive=["button","a","select","input","textarea","canvas"].includes(tag)||interactiveRole||contentEditable||html.tabIndex>=0;const focusable=nativeText||['button','a','select','input','textarea'].includes(tag)||contentEditable||html.tabIndex>=0;const path:string[]=[];let current:Element|null=element;while(current&&path.length<8){path.unshift(`${current.tagName.toLowerCase()}:${current.parentElement?Array.from(current.parentElement.children).indexOf(current):0}`);current=current.parentElement;}
  const all=Array.from(element.ownerDocument.querySelectorAll("body *"));const elementIndex=all.indexOf(element);const relationMatches=relations.map((relation)=>{const expected=(relation.name??"").normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim();if(!expected)return true;const anchors=all.filter((candidate)=>`${candidate.getAttribute("aria-label")??""} ${candidate.getAttribute("title")??""} ${candidate.textContent??""}`.normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim().includes(expected));if(relation.kind==="labelled_by")return labels.some((value)=>value.normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim().includes(expected));if(relation.kind==="described_by")return(element.getAttribute("aria-description")??element.getAttribute("title")??"").normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim().includes(expected);if(relation.kind==="contains")return(element.textContent??"").normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim().includes(expected);if(relation.kind==="belongs_to_field_group"||relation.kind==="same_boundary")return(element.closest("fieldset,[role=group],form,dl,div")?.textContent??"").normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim().includes(expected);if(relation.kind==="recently_created")return element.matches("[data-scry-recently-created],[data-scry-recently-changed]");return anchors.some((anchor)=>{const anchorIndex=all.indexOf(anchor);const a=(anchor as HTMLElement).getBoundingClientRect();const sameBand=Math.abs((a.y+a.height/2)-(rect.y+rect.height/2))<=Math.max(a.height,rect.height);if(relation.kind==="following")return anchorIndex>=0&&anchorIndex<elementIndex;if(relation.kind==="below")return rect.y>=a.y+a.height&&Math.abs((a.x+a.width/2)-(rect.x+rect.width/2))<Math.max(a.width,rect.width);if(relation.kind==="right_of")return rect.x>=a.x+a.width&&sameBand;if(relation.kind==="same_horizontal_band")return sameBand;if(relation.kind==="nearby"||relation.kind==="table_cell_of")return Math.hypot((a.x+a.width/2)-(rect.x+rect.width/2),(a.y+a.height/2)-(rect.y+rect.height/2))<300;return false;});});
  for(let index=0;index<relations.length;index+=1){const relation=relations[index]!;if(relation.kind!=="following"||!relationMatches[index])continue;const expected=(relation.name??"").normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim();const own=(element.textContent??"").normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim();if(expected&&own.includes(expected))relationMatches[index]=false;}
  return{runtimeId,tag,role,name,accessibilityRole:"",accessibilityName:"",labels:[...new Set(labels)],description:(element.getAttribute("aria-description")??element.getAttribute("title")??"").trim(),text:(element.textContent??"").replace(/\s+/g," ").trim().slice(0,500),placeholder,inputType:tag==="input"?input.type:"",context:(element.parentElement?.textContent??"").replace(/\s+/g," ").trim().slice(0,500),path,bounds:{x:rect.x,y:rect.y,width:rect.width,height:rect.height},capabilities:{canFocus:focusable,canReceivePointer:visible&&style.pointerEvents!=="none"&&pointerInteractive,canActivateWithKeyboard:focusable&&(role==="button"||role==="link"||tag==="button"||tag==="a"),canAcceptText:nativeText||contentEditable,canToggle:input.type==="checkbox"||input.type==="radio"||role==="checkbox"||role==="radio"||role==="switch",canSelectOption:tag==="select"||role==="combobox"||role==="listbox",canSubmit:tag==="button"&&(input.type==="submit"||element.getAttribute("type")===null),canReadValue:nativeText||tag==="select"||contentEditable||["output","code","pre","dd","dt","main","section","p","span","div","h1","h2","h3","h4","h5","h6"].includes(tag)||element.hasAttribute("data-scry-readable"),visible,enabled:!disabled,editable:(nativeText||contentEditable)&&!readonly&&!disabled,readonly,nativeKind:tag,computedRole:role,accessibleName:name||undefined,placeholder:placeholder||undefined,inputType:tag==="input"?input.type:undefined},relationMatches};
}

function capabilityViolations(intent:InteractionTargetIntent,meta:ObservedControl){const c=meta.capabilities;const values:Record<string,boolean>={focusable:c.canFocus,pointer_activatable:c.canReceivePointer,keyboard_activatable:c.canActivateWithKeyboard,accepts_text:c.canAcceptText,editable:c.editable,toggleable:c.canToggle,selects_option:c.canSelectOption,submittable:c.canSubmit,readable_value:c.canReadValue,coordinate_action:meta.tag==="canvas"};const failures:string[]=intent.requiredCapabilities.filter((item)=>!values[item]);if(intent.requiredCapabilities.includes("coordinate_action")&&!intent.preferredEvidence.visual?.sources.includes("canvas"))failures.push("canvas_evidence_required");if(intent.requiredCapabilities.includes("coordinate_action")&&!['read_only','ordinary'].includes(intent.risk))failures.push("coordinate_action_risk");for(let index=0;index<intent.relations.length;index+=1)if(!meta.relationMatches[index])failures.push(`relation:${intent.relations[index]!.kind}`);if(intent.prohibited.includes("hidden")&&!c.visible)failures.push("hidden");if(intent.prohibited.includes("disabled")&&!c.enabled)failures.push("disabled");if(intent.prohibited.includes("readonly")&&c.readonly)failures.push("readonly");if(intent.prohibited.includes("display_only_text")&&!c.canAcceptText&&!c.canReceivePointer)failures.push("display_only_text");return failures;}
function parseAriaSnapshot(snapshot:string){const line=snapshot.split("\n").find((item)=>item.trim().startsWith("- "))?.trim()??"";const match=/^- ([a-zA-Z0-9_-]+)(?: \"([^\"]*)\")?/.exec(line);return{role:match?.[1]??"",name:match?.[2]??""};}
function scoreEvidence(_intent:InteractionTargetIntent,evidence:CandidateEvidence[]):GroundingScore{return PraxisGroundingPolicyV1.score(evidence);}
function selectAdapter(intent:InteractionTargetIntent,meta:ObservedControl):InteractionAdapter{if(intent.requiredCapabilities.includes("coordinate_action"))return"canvas_coordinate";if(intent.requiredCapabilities.includes("accepts_text"))return meta.tag==="input"||meta.tag==="textarea"?"native_fill":meta.capabilities.editable?"content_editable":"focus_keyboard";if(intent.requiredCapabilities.includes("toggleable"))return"native_check";if(intent.requiredCapabilities.includes("selects_option"))return"native_select";return"native_click";}
function riskPolicy(intent:InteractionTargetIntent){const high=["destructive","authentication","credential","protected","live"].includes(intent.risk);return{minimum:intent.confidence.minimum??(high?0.76:0.58),margin:intent.confidence.minimumMargin??(high?0.14:0.08),familyCount:intent.confidence.minimumFamilyCount??(high?3:intent.risk==="read_only"?1:2)};}
function degradedPermitted(intent:InteractionTargetIntent,channel:string){return channel==="visual"&&!["destructive","credential","protected","live"].includes(intent.risk);}
function fingerprint(intent:InteractionTargetIntent,meta:ObservedControl):SemanticFingerprint{const capabilityDigest=createHash("sha256").update(JSON.stringify(meta.capabilities)).digest("hex");return{version:2,digest:createHash("sha256").update(JSON.stringify({concept:intent.concept,path:meta.path,capabilityDigest})).digest("hex"),concept:intent.concept,scopeKind:intent.scope.kind,capabilityDigest,structuralPath:meta.path};}
function normalize(value:string){return value.normalize("NFKC").toLowerCase().replace(/\s+/g," ").trim();}
function stableJson(value:unknown):string{if(Array.isArray(value))return`[${value.map(stableJson).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stableJson(item)}`).join(",")}}`;return JSON.stringify(value);}
function emptyDiagnostic(scope:InteractionTargetIntent["scope"],count:number):GroundingDiagnostic{return{candidateCount:count,eligibleCount:0,confidence:0,confidenceMargin:0,scope,rejectedConstraints:["scope"],drift:"unchanged",safeActions:["narrow_scope","revise_intent"],resolutionSource:"unified",visualCandidateCount:0,observation:{status:"succeeded"}};}
function observationError(intentDigest:string,intent:InteractionTargetIntent,count:number,phase:string,error:unknown){const diagnostic:GroundingDiagnostic={...emptyDiagnostic(intent.scope,count),observation:{status:"failed",phase,reasonCode:error instanceof Error?error.name:"UNKNOWN"},safeActions:["check_executor_health"]};return new GroundingError("OBSERVATION_FAILED",diagnostic,intentDigest);}
async function throwObservation(page:Page,intentDigest:string,intent:InteractionTargetIntent,count:number,phase:string,error:unknown):Promise<never>{const failure=observationError(intentDigest,intent,count,phase,error);await observers.get(page)?.({...failure.diagnostic,code:failure.code,intentDigest,outcome:"rejected"});throw failure;}
async function reject(page:Page,intentDigest:string,code:string,diagnostic:GroundingDiagnostic){await observers.get(page)?.({...diagnostic,code,intentDigest,outcome:"rejected"});return new GroundingError(code,diagnostic);}
export class GroundingError extends Error{constructor(public readonly code:string,public readonly diagnostic:GroundingDiagnostic,public readonly intentDigest?:string){super(code);this.name="GroundingError";}}
export class ExpectedEffectError extends Error{constructor(public readonly code:string){super(code);this.name="ExpectedEffectError";}}
